import type { CurriculumItem } from "./types.js";

export const MEXT_EDUCATION_DATA_STANDARD_URL =
  "https://www.mext.go.jp/a_menu/other/data_00001.htm";

const source = {
  publisher: "文部科学省" as const,
  url: MEXT_EDUCATION_DATA_STANDARD_URL,
  note: "学習指導要領コード表を根拠にしたseed正規化データ。正式コードの全量取り込みは今後のimporterで行う。",
};

export const curriculumItems: CurriculumItem[] = [
  {
    id: "math-e1-add-sub",
    stage: "小学校",
    grade: 1,
    subject: "算数",
    domain: "数と計算",
    topic: "たし算・ひき算",
    aliases: ["足し算", "引き算", "加法", "減法", "たしざん", "ひきざん"],
    description: "具体物や数を用いた基本的なたし算・ひき算。",
    prerequisites: [],
    source,
  },
  {
    id: "math-e2-multiplication",
    stage: "小学校",
    grade: 2,
    subject: "算数",
    domain: "数と計算",
    topic: "かけ算",
    aliases: ["掛け算", "九九", "乗法"],
    description: "乗法の意味と九九を含む基本的なかけ算。",
    prerequisites: ["math-e1-add-sub"],
    source,
  },
  {
    id: "math-e3-division",
    stage: "小学校",
    grade: 3,
    subject: "算数",
    domain: "数と計算",
    topic: "わり算",
    aliases: ["割り算", "除法", "あまりのあるわり算"],
    description: "除法の意味と基本的な計算。",
    prerequisites: ["math-e2-multiplication"],
    source,
  },
  {
    id: "math-e4-decimal-fraction",
    stage: "小学校",
    grade: 4,
    subject: "算数",
    domain: "数と計算",
    topic: "小数・分数の基礎計算",
    aliases: ["小数", "分数", "同分母分数", "小数の計算"],
    description: "小数や分数の意味を広げ、基本的な計算を扱う。",
    prerequisites: ["math-e3-division"],
    source,
  },
  {
    id: "math-e5-percentage",
    stage: "小学校",
    grade: 5,
    subject: "算数",
    domain: "変化と関係",
    topic: "割合・百分率",
    aliases: ["割合", "百分率", "パーセント", "％", "単位量あたり"],
    description: "割合、百分率、単位量当たりの大きさを扱う。",
    prerequisites: ["math-e4-decimal-fraction"],
    source,
  },
  {
    id: "math-e6-ratio-proportion",
    stage: "小学校",
    grade: 6,
    subject: "算数",
    domain: "変化と関係",
    topic: "比・比例・反比例",
    aliases: ["比", "比例", "反比例", "比の値"],
    description: "比とその値、比例・反比例の関係を扱う。",
    prerequisites: ["math-e5-percentage"],
    source,
  },
  {
    id: "math-j1-negative",
    stage: "中学校",
    grade: 1,
    subject: "数学",
    domain: "数と式",
    topic: "正の数・負の数",
    aliases: ["正負の数", "負の数", "絶対値"],
    description: "正負の数の意味、四則計算、絶対値。",
    prerequisites: ["math-e6-ratio-proportion"],
    source,
  },
  {
    id: "math-j1-linear-equation",
    stage: "中学校",
    grade: 1,
    subject: "数学",
    domain: "数と式",
    topic: "一元一次方程式",
    aliases: ["一次方程式", "方程式", "移項"],
    description: "一元一次方程式とその利用。",
    prerequisites: ["math-j1-negative"],
    source,
  },
  {
    id: "math-j1-proportion",
    stage: "中学校",
    grade: 1,
    subject: "数学",
    domain: "関数",
    topic: "比例・反比例",
    aliases: ["比例定数", "反比例のグラフ", "比例のグラフ"],
    description: "座標とグラフを用いた比例・反比例。",
    prerequisites: ["math-e6-ratio-proportion", "math-j1-negative"],
    source,
  },
  {
    id: "math-j2-simultaneous",
    stage: "中学校",
    grade: 2,
    subject: "数学",
    domain: "数と式",
    topic: "連立二元一次方程式",
    aliases: ["連立方程式", "加減法", "代入法"],
    description: "連立二元一次方程式とその利用。",
    prerequisites: ["math-j1-linear-equation"],
    source,
  },
  {
    id: "math-j2-linear-function",
    stage: "中学校",
    grade: 2,
    subject: "数学",
    domain: "関数",
    topic: "一次関数",
    aliases: ["一次関数", "傾き", "切片", "変化の割合"],
    description: "一次関数、グラフ、変化の割合と利用。",
    prerequisites: ["math-j1-proportion", "math-j2-simultaneous"],
    source,
  },
  {
    id: "math-j2-congruence-proof",
    stage: "中学校",
    grade: 2,
    subject: "数学",
    domain: "図形",
    topic: "三角形の合同と証明",
    aliases: ["合同条件", "三角形の合同", "証明", "平行線と角"],
    description: "三角形の合同条件を使った論証。",
    prerequisites: [],
    source,
  },
  {
    id: "math-j2-probability",
    stage: "中学校",
    grade: 2,
    subject: "数学",
    domain: "データの活用",
    topic: "確率",
    aliases: ["確率", "同様に確からしい"],
    description: "多数回の試行や場合の数を基礎とした確率。",
    prerequisites: [],
    source,
  },
  {
    id: "math-j3-square-root",
    stage: "中学校",
    grade: 3,
    subject: "数学",
    domain: "数と式",
    topic: "平方根",
    aliases: ["平方根", "ルート", "根号", "√"],
    description: "平方根の意味と根号を含む式の計算。",
    prerequisites: ["math-j1-negative"],
    source,
  },
  {
    id: "math-j3-quadratic-equation",
    stage: "中学校",
    grade: 3,
    subject: "数学",
    domain: "数と式",
    topic: "二次方程式",
    aliases: ["二次方程式", "解の公式", "平方完成"],
    description: "因数分解や平方根、解の公式を用いた二次方程式。",
    prerequisites: ["math-j3-square-root", "math-j1-linear-equation"],
    source,
  },
  {
    id: "math-j3-quadratic-function",
    stage: "中学校",
    grade: 3,
    subject: "数学",
    domain: "関数",
    topic: "関数 y=ax^2",
    aliases: ["y=ax^2", "二乗に比例する関数", "放物線"],
    description: "関数 y=ax^2 の変化とグラフ。",
    prerequisites: ["math-j2-linear-function"],
    source,
  },
  {
    id: "math-j3-similarity",
    stage: "中学校",
    grade: 3,
    subject: "数学",
    domain: "図形",
    topic: "相似な図形",
    aliases: ["相似", "相似条件", "相似比"],
    description: "三角形などの相似条件と相似比の利用。",
    prerequisites: ["math-j2-congruence-proof"],
    source,
  },
  {
    id: "math-j3-pythagorean",
    stage: "中学校",
    grade: 3,
    subject: "数学",
    domain: "図形",
    topic: "三平方の定理",
    aliases: ["三平方", "ピタゴラスの定理", "a^2+b^2=c^2"],
    description: "直角三角形の三辺の関係とその利用。",
    prerequisites: ["math-j3-square-root", "math-j3-similarity"],
    source,
  },
  {
    id: "math-j3-sampling",
    stage: "中学校",
    grade: 3,
    subject: "数学",
    domain: "データの活用",
    topic: "標本調査",
    aliases: ["標本調査", "母集団", "標本"],
    description: "母集団から標本を取り出し傾向を推測する考え方。",
    prerequisites: [],
    source,
  },
  {
    id: "math-h1-quadratic-function",
    stage: "高等学校",
    subject: "数学I",
    domain: "二次関数",
    topic: "二次関数",
    aliases: ["二次関数", "二次関数の最大最小", "判別式"],
    description: "二次関数のグラフ、最大・最小、二次不等式など。",
    prerequisites: ["math-j3-quadratic-equation", "math-j3-quadratic-function"],
    source,
  },
  {
    id: "math-h1-trig-ratio",
    stage: "高等学校",
    subject: "数学I",
    domain: "図形と計量",
    topic: "三角比",
    aliases: ["三角比", "sin", "cos", "tan", "正弦定理", "余弦定理"],
    description: "三角比と図形の計量。",
    prerequisites: ["math-j3-pythagorean"],
    source,
  },
  {
    id: "math-h1-data",
    stage: "高等学校",
    subject: "数学I",
    domain: "データの分析",
    topic: "分散・標準偏差・相関",
    aliases: ["分散", "標準偏差", "相関係数", "散布図"],
    description: "データの散らばりや相関を数量的に扱う。",
    prerequisites: ["math-j3-sampling"],
    source,
  },
  {
    id: "math-h2-explog",
    stage: "高等学校",
    subject: "数学II",
    domain: "指数関数・対数関数",
    topic: "指数関数・対数関数",
    aliases: ["指数関数", "対数関数", "log", "常用対数"],
    description: "指数法則を拡張し、指数関数・対数関数を扱う。",
    prerequisites: ["math-h1-quadratic-function"],
    source,
  },
  {
    id: "math-h2-trig-function",
    stage: "高等学校",
    subject: "数学II",
    domain: "三角関数",
    topic: "三角関数",
    aliases: ["三角関数", "加法定理", "弧度法", "ラジアン"],
    description: "一般角、弧度法、三角関数、加法定理。",
    prerequisites: ["math-h1-trig-ratio"],
    source,
  },
  {
    id: "math-h2-calculus",
    stage: "高等学校",
    subject: "数学II",
    domain: "微分・積分の考え",
    topic: "微分法・積分法",
    aliases: ["微分", "導関数", "接線", "積分", "定積分", "不定積分"],
    description: "多項式関数を中心とする微分・積分とその応用。",
    prerequisites: ["math-h1-quadratic-function"],
    source,
  },
  {
    id: "math-hb-sequence",
    stage: "高等学校",
    subject: "数学B",
    domain: "数列",
    topic: "数列",
    aliases: ["数列", "等差数列", "等比数列", "漸化式", "Σ", "シグマ"],
    description: "等差・等比数列、和、漸化式など。",
    prerequisites: ["math-j3-quadratic-equation"],
    source,
  },
  {
    id: "math-hc-vector",
    stage: "高等学校",
    subject: "数学C",
    domain: "ベクトル",
    topic: "ベクトル",
    aliases: ["ベクトル", "内積", "位置ベクトル"],
    description: "平面・空間のベクトルと内積など。",
    prerequisites: ["math-j2-congruence-proof"],
    source,
  },
  {
    id: "english-j-present-perfect",
    stage: "中学校",
    grade: 3,
    subject: "英語",
    domain: "文法",
    topic: "現在完了",
    aliases: ["現在完了形", "have been", "have done", "has been", "has done"],
    description: "経験・継続・完了などを表す現在完了。",
    prerequisites: [],
    source,
  },
  {
    id: "english-j-relative-pronoun",
    stage: "中学校",
    grade: 3,
    subject: "英語",
    domain: "文法",
    topic: "関係代名詞",
    aliases: ["関係代名詞", "who", "which", "that"],
    description: "名詞を後ろから修飾する関係代名詞を含む表現。",
    prerequisites: [],
    source,
  },
  {
    id: "japanese-j-classical",
    stage: "中学校",
    subject: "国語",
    domain: "伝統的な言語文化",
    topic: "古文・漢文の基礎",
    aliases: ["古文", "漢文", "歴史的仮名遣い", "訓読"],
    description: "古典に親しむための基礎的な読み方や表現。",
    prerequisites: [],
    source,
  },
];

export const curriculumById = new Map(
  curriculumItems.map((item) => [item.id, item]),
);
